language: objective-c
osx_image: xcode7.3
xcode_project: OneSignal.xcodeproj
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: OneSignal-Dynamic
xcode_sdk: iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=OneSignal
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - cd iOS_SDK/  
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
